### ISSUE TITLE
An error during the creation of any craft 

### ISSUE THREAD

**Issue by SEDIIK** [jaredlll08/IceAndFireTweaker#6]
Hello, I'm having trouble creating a craft in Dragon forge. When I reload the scripts, get an unclear error.
![Снимок](https://github.com/jaredlll08/IceAndFireTweaker/assets/130316398/d86401cc-b1d8-444f-b2a8-8d39878f9269)
```zenscript
mods.iceandfire.DragonForge.addFireRecipe(<item:miningmaster:fire_ruby>, <item:minecraft:emerald>, <item:iceandfire:fire_dragon_blood>);
``` 
Mods versions
Ice and fire 2.1.12
Ice And Fire Tweaker 1.0.0.5
CraftTweaker 7.1.2.520

**Comment by jaredlll08** [comment]
Upload your crafttweaker.log file to pastebin and give the link please.
you can use `/ct log` to open it.

**Comment by SEDIIK** [comment]
https://pastebin.com/af2WdiDJ

**Comment by jaredlll08** [comment]
The scripting syntax has changed to account for their changes, please update your script accordingly:
https://github.com/jaredlll08/IceAndFireTweaker/blob/main/src/main/resources/data/iceandfiretweaker/scripts/iceandfire/dragonforge.zs

**Comment by SEDIIK** [comment]
![Снимок](https://github.com/jaredlll08/IceAndFireTweaker/assets/130316398/6cd5a335-95eb-46e0-a1b8-14407c504491)
```zenscript
<recipetype:iceandfire:dragonforge>.addFireRecipe("fire_recipe_test_3", <item:minecraft:diamond>, <item:minecraft:red_wool>, <item:minecraft:blue_wool>, 200);
``` 
https://pastebin.com/3SdRLWe7

**Comment by jaredlll08** [comment]
https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-tweaker/files/4537528
Update ice and fire tweaker.

**Comment by SEDIIK** [comment]
Thank you! For some reason I hadn't seen this update before🤔
